# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(A)
print(A.ndim)
print(A.shape)
print(A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(B,'\n')

print(np.exp(B),'\n') #beräknar e^i där i är värdet på motsvarande index.

print(np.min(B),'\n')

for row in B:
    print(np.min(row))
print()

for row in B.T:
    print(np.min(row))
print()


print(np.argmin(B),'\n')

i = 0
for row in B:
    print(np.argmin(B) + 3*i)
    i += 1
print()

print(np.sum(B),'\n')
print(np.sum(B, axis=1),'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

1 

1
4
7

1
2
3

0 

0
3
6

45 

[ 6 15 24] 



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [17]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
print(A[1])
print()
print(A[0, 2])


[ 6  7  8  9 10]

3


**Answer:**

In [ ]:
Då tolkas det som att den återstående "axes" är complete, dvs A[1] ger samma svar som A[1, :] (vilket kan tolkas som "skriv ut raden med index 1 i A, : säger att alla kolumner ska ingå")

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [25]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [31]:
#Jag hade använt mig av:
for i in np.nditer(A):
    print(i)


#Ett alternativ hade varit:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [34]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Svar
Eftersom vi ger reshape 3 värden så ber vi om en 3dimensionell array.
Värdena hamnar då som x, y, z. När vi skickar in (2, 3, -1) så tolkas det som att
vi vill ha två element i x-led (gör så det ser ut som två olika matriser).

Vi vill sen ha tre element i y-led (varje matris har 3 rader).
-1 används för att berätta för reshape att "i detta leden fyller du på så det passar". 


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [38]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [39]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [40]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [145]:
def add_mult_matrices(A, B, operation):
    if (isinstance(a, np.ndarray) and (isinstance(b, np.ndarray))) is False:
        return 'Enter two arrays'
    
  
    if (operation == 'add' or operation == 'multiply') != True:
        return 'Chose either add or multiply'
    
    
    if operation == 'add':
        if A.shape != B.shape:
            return 'They have to be the same size for addition'
        else:
            return (A + B)

    elif operation == 'multiply':
        if (A.shape[-1] != B.shape[0]):
            print('Sizes does not conform')
        else:
            C =np.array(A @ B)
            return(C)


    
test_A = np.array([[1, 2, 3], [4, 5, 6]])
test_B = np.array([[2, 3], [3, 4], [4, 5]])

c = add_mult_matrices(test_A, test_B, 'multiply')
print(c)

[[20 26]
 [47 62]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [90]:
# 10.1.1
x = np.array([[4,3]])
#Använder dubbla brackets här för att i senare uppgift kunna ta fram transponatet. 
print('10.1.1')
#a)
print('a: ', x.shape)

#b)
print('b: ', 5 * x)

#c)
print('c: ', 3 * x)

#d)
print('d: ', (5 * x) + (3 * x))

#e
print('e: ', 8 * x)

#f
print('f: ', (4 * x) - (x))

#g
print('g) \n', x.T, '\ndim: ', (x.T).shape)

#h
#Nej, x + x.T är ej definerat då dimensionerna inte stämmer.

#i
x_1, x_2 = x[0]
calc = ((x_1**2) + (x_2**1))**0.5
print('i) ||x|| = ', calc)


10.1.1
a:  (1, 2)
b:  [[20 15]]
c:  [[12  9]]
d:  [[32 24]]
e:  [[32 24]]
f:  [[12  9]]
g) 
 [[4]
 [3]] 
dim:  (2, 1)
i) ||x|| =  4.358898943540674


In [122]:
#10.1.2
print('10.1.2')

v = (np.array([[3, 7, 0, 11]])).T
print(v)

#a
print('a har dim: ', v.shape)

#b
print('b: \n', 2*v)

#c
print('c: \n', 5*v - 2*v)

#d
print('d: \n', 4*v - 2*v)

#e
print('e: \n', v.T, 'dim: ', v.T.shape)

#f
v_1, v_2, v_3, v_4 = v
calc_v = (((v_1)**2) + ((v_2)**2) + ((v_3)**2) + ((v_4)**2))**0.5
print('f) ||v|| = ', calc_v)
print()

10.1.2
[[ 3]
 [ 7]
 [ 0]
 [11]]
a har dim:  (4, 1)
b: 
 [[ 6]
 [14]
 [ 0]
 [22]]
c: 
 [[ 9]
 [21]
 [ 0]
 [33]]
d: 
 [[ 6]
 [14]
 [ 0]
 [22]]
e: 
 [[ 3  7  0 11]] dim:  (1, 4)
f) ||v|| =  [13.37908816]



In [126]:
#10.1.3 använder u_1 och u_2 då v använts i tidigare uppgift

u_1 = np.array([[4, 3, 1, 5]]).T
u_2 = np.array([[2, 3, 1, 1]]).T

u_1_1, u_1_2, u_1_3, u_1_4 = u_1
u_2_1, u_2_2, u_2_3, u_2_4 = u_2

u_3 = np.array(u_1 - u_2)
u_3_1, u_3_2, u_3_3, u_3_4 = u_3

calc_u_1 = (((u_1_1)**2) + ((u_1_2)**2) + ((u_1_3)**2) + ((u_1_4)**2))**0.5
print('a) ||u_1|| = ', calc_u_1)

calc_u_3 = (((u_3_1)**2) + ((u_3_2)**2) + ((u_3_3)**2) + ((u_3_4)**2))**0.5
print('b) ||u_1 - u_2 || = ', calc_u_3 )

print()

a) ||u_1|| =  [7.14142843]
b) ||u_1 - u_2 || =  [4.47213595]



### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [147]:
#10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

#a)
print(2 * A)
#b)
print('a)', add_mult_matrices(B, (-2*A), 'add'))
#c)
print('\nb', add_mult_matrices(3*C, -2*E, 'add'))
#d)
print('\nc', add_mult_matrices(2*D, -3*C, 'add'))
#e)
print('\nd', add_mult_matrices(D.T, 2*D, 'add'))
#f)
print('\ne', add_mult_matrices(2*C.T, -2*D.T, 'add'))
#g)
print('\nf', add_mult_matrices(A.T, -B, 'add'))
#h)
print('\ng', add_mult_matrices(A, C, 'multiply'))
#g)
print('\nh', add_mult_matrices(A, D, 'multiply'))
#i) 
print('\ni', add_mult_matrices(C, D, 'multiply'))
#j)
print('\nj', add_mult_matrices(C, B, 'multiply'))
#k
print('\nk', add_mult_matrices(C, I, 'multiply'))
#l
print('\nl', add_mult_matrices(A, B.T, 'multiply'))

[[ 4  2 -2]
 [ 2 -2  2]]
a) [[ 0 -4  3]
 [ 0 -2 -4]]

b They have to be the same size for addition

c [[3 2]
 [2 3]]

d [[ 9 12]
 [12  9]]

e [[-4 -4]
 [-4 -4]]

f They have to be the same size for addition
Sizes does not conform

g None
Sizes does not conform

h None

i [[11 10]
 [10 11]]

j [[  8 -10  -3]
 [ 10  -8   0]]

k [[1 2]
 [2 1]]

l [[5 2]
 [7 4]]


In [150]:
#10.2.2
A = np.array([[2, 3, 4],[5, 4, 1]])

result = add_mult_matrices(A, A.T, 'multiply')
print(result)

[[29 26]
 [26 42]]


In [151]:
#10.2.3
A = np.array([[1, 2],[2, 4]])
B = np.array([[2, 1],[1, 3]])
C = np.array([[4, 3],[0, 2]])

A_B = add_mult_matrices(A, B, 'multiply')
print(A_B)

A_C = add_mult_matrices(A, C, 'multiply')
print(A_C)

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [162]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

v1[1] = 5
v2[1] = 1
# I detta fall är v2 en view. Både v1 och v2 tittar på samma minne, och ändrar vi i någon av dom så ändras minnesbiten, inte en kopia. 
# Vi kan se att det är simple indexing, dvs att det antingen använts ett index eller ett intervall med :, vilket leder till view. 
print(v1)
print(v2)


[0 1 2 3]
[2 3]
[0 5 2 1]
[2 1]


In [159]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)